// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bapkkdliemspedgozdhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhcGtrZGxpZW1zcGVkZ296ZGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDI4OTcsImV4cCI6MjA2MzM3ODg5N30.5bNZ3Z3Hea_MsiG1jJrp9D-Ft4LnI3gxuI1R41uP9Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);